# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/inocxh/Dokumenter/DTU/6.semester/bachelor/top-trees

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/inocxh/Dokumenter/DTU/6.semester/bachelor/top-trees

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/inocxh/Dokumenter/DTU/6.semester/bachelor/top-trees/CMakeFiles /home/inocxh/Dokumenter/DTU/6.semester/bachelor/top-trees//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/inocxh/Dokumenter/DTU/6.semester/bachelor/top-trees/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/Catch2/src/CMakeFiles/Catch2.dir/build.make src/lib/Catch2/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/Catch2/src/CMakeFiles/Catch2WithMain.dir/build.make src/lib/Catch2/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

src/connected.o: src/connected.cpp.o
.PHONY : src/connected.o

# target to build an object file
src/connected.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/connected.cpp.o
.PHONY : src/connected.cpp.o

src/connected.i: src/connected.cpp.i
.PHONY : src/connected.i

# target to preprocess a source file
src/connected.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/connected.cpp.i
.PHONY : src/connected.cpp.i

src/connected.s: src/connected.cpp.s
.PHONY : src/connected.s

# target to generate assembly for a file
src/connected.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/connected.cpp.s
.PHONY : src/connected.cpp.s

src/cover_level.o: src/cover_level.cpp.o
.PHONY : src/cover_level.o

# target to build an object file
src/cover_level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/cover_level.cpp.o
.PHONY : src/cover_level.cpp.o

src/cover_level.i: src/cover_level.cpp.i
.PHONY : src/cover_level.i

# target to preprocess a source file
src/cover_level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/cover_level.cpp.i
.PHONY : src/cover_level.cpp.i

src/cover_level.s: src/cover_level.cpp.s
.PHONY : src/cover_level.s

# target to generate assembly for a file
src/cover_level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/cover_level.cpp.s
.PHONY : src/cover_level.cpp.s

src/find_size.o: src/find_size.cpp.o
.PHONY : src/find_size.o

# target to build an object file
src/find_size.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/find_size.cpp.o
.PHONY : src/find_size.cpp.o

src/find_size.i: src/find_size.cpp.i
.PHONY : src/find_size.i

# target to preprocess a source file
src/find_size.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/find_size.cpp.i
.PHONY : src/find_size.cpp.i

src/find_size.s: src/find_size.cpp.s
.PHONY : src/find_size.s

# target to generate assembly for a file
src/find_size.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/find_size.cpp.s
.PHONY : src/find_size.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/two_edge_cluster.o: src/two_edge_cluster.cpp.o
.PHONY : src/two_edge_cluster.o

# target to build an object file
src/two_edge_cluster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/two_edge_cluster.cpp.o
.PHONY : src/two_edge_cluster.cpp.o

src/two_edge_cluster.i: src/two_edge_cluster.cpp.i
.PHONY : src/two_edge_cluster.i

# target to preprocess a source file
src/two_edge_cluster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/two_edge_cluster.cpp.i
.PHONY : src/two_edge_cluster.cpp.i

src/two_edge_cluster.s: src/two_edge_cluster.cpp.s
.PHONY : src/two_edge_cluster.s

# target to generate assembly for a file
src/two_edge_cluster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/two_edge_cluster.cpp.s
.PHONY : src/two_edge_cluster.cpp.s

src/two_edge_connected.o: src/two_edge_connected.cpp.o
.PHONY : src/two_edge_connected.o

# target to build an object file
src/two_edge_connected.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/two_edge_connected.cpp.o
.PHONY : src/two_edge_connected.cpp.o

src/two_edge_connected.i: src/two_edge_connected.cpp.i
.PHONY : src/two_edge_connected.i

# target to preprocess a source file
src/two_edge_connected.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/two_edge_connected.cpp.i
.PHONY : src/two_edge_connected.cpp.i

src/two_edge_connected.s: src/two_edge_connected.cpp.s
.PHONY : src/two_edge_connected.s

# target to generate assembly for a file
src/two_edge_connected.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/two_edge_connected.cpp.s
.PHONY : src/two_edge_connected.cpp.s

test/2_edge_tests/connected_test.o: test/2_edge_tests/connected_test.cpp.o
.PHONY : test/2_edge_tests/connected_test.o

# target to build an object file
test/2_edge_tests/connected_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/2_edge_tests/connected_test.cpp.o
.PHONY : test/2_edge_tests/connected_test.cpp.o

test/2_edge_tests/connected_test.i: test/2_edge_tests/connected_test.cpp.i
.PHONY : test/2_edge_tests/connected_test.i

# target to preprocess a source file
test/2_edge_tests/connected_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/2_edge_tests/connected_test.cpp.i
.PHONY : test/2_edge_tests/connected_test.cpp.i

test/2_edge_tests/connected_test.s: test/2_edge_tests/connected_test.cpp.s
.PHONY : test/2_edge_tests/connected_test.s

# target to generate assembly for a file
test/2_edge_tests/connected_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/2_edge_tests/connected_test.cpp.s
.PHONY : test/2_edge_tests/connected_test.cpp.s

test/2_edge_tests/cover_level_test.o: test/2_edge_tests/cover_level_test.cpp.o
.PHONY : test/2_edge_tests/cover_level_test.o

# target to build an object file
test/2_edge_tests/cover_level_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/2_edge_tests/cover_level_test.cpp.o
.PHONY : test/2_edge_tests/cover_level_test.cpp.o

test/2_edge_tests/cover_level_test.i: test/2_edge_tests/cover_level_test.cpp.i
.PHONY : test/2_edge_tests/cover_level_test.i

# target to preprocess a source file
test/2_edge_tests/cover_level_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/2_edge_tests/cover_level_test.cpp.i
.PHONY : test/2_edge_tests/cover_level_test.cpp.i

test/2_edge_tests/cover_level_test.s: test/2_edge_tests/cover_level_test.cpp.s
.PHONY : test/2_edge_tests/cover_level_test.s

# target to generate assembly for a file
test/2_edge_tests/cover_level_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/2_edge_tests/cover_level_test.cpp.s
.PHONY : test/2_edge_tests/cover_level_test.cpp.s

test/2_edge_tests/find_size_test.o: test/2_edge_tests/find_size_test.cpp.o
.PHONY : test/2_edge_tests/find_size_test.o

# target to build an object file
test/2_edge_tests/find_size_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/2_edge_tests/find_size_test.cpp.o
.PHONY : test/2_edge_tests/find_size_test.cpp.o

test/2_edge_tests/find_size_test.i: test/2_edge_tests/find_size_test.cpp.i
.PHONY : test/2_edge_tests/find_size_test.i

# target to preprocess a source file
test/2_edge_tests/find_size_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/2_edge_tests/find_size_test.cpp.i
.PHONY : test/2_edge_tests/find_size_test.cpp.i

test/2_edge_tests/find_size_test.s: test/2_edge_tests/find_size_test.cpp.s
.PHONY : test/2_edge_tests/find_size_test.s

# target to generate assembly for a file
test/2_edge_tests/find_size_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/2_edge_tests/find_size_test.cpp.s
.PHONY : test/2_edge_tests/find_size_test.cpp.s

test/toptree_tests/add_common_weight_test.o: test/toptree_tests/add_common_weight_test.cpp.o
.PHONY : test/toptree_tests/add_common_weight_test.o

# target to build an object file
test/toptree_tests/add_common_weight_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/add_common_weight_test.cpp.o
.PHONY : test/toptree_tests/add_common_weight_test.cpp.o

test/toptree_tests/add_common_weight_test.i: test/toptree_tests/add_common_weight_test.cpp.i
.PHONY : test/toptree_tests/add_common_weight_test.i

# target to preprocess a source file
test/toptree_tests/add_common_weight_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/add_common_weight_test.cpp.i
.PHONY : test/toptree_tests/add_common_weight_test.cpp.i

test/toptree_tests/add_common_weight_test.s: test/toptree_tests/add_common_weight_test.cpp.s
.PHONY : test/toptree_tests/add_common_weight_test.s

# target to generate assembly for a file
test/toptree_tests/add_common_weight_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/add_common_weight_test.cpp.s
.PHONY : test/toptree_tests/add_common_weight_test.cpp.s

test/toptree_tests/diameter_test.o: test/toptree_tests/diameter_test.cpp.o
.PHONY : test/toptree_tests/diameter_test.o

# target to build an object file
test/toptree_tests/diameter_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/diameter_test.cpp.o
.PHONY : test/toptree_tests/diameter_test.cpp.o

test/toptree_tests/diameter_test.i: test/toptree_tests/diameter_test.cpp.i
.PHONY : test/toptree_tests/diameter_test.i

# target to preprocess a source file
test/toptree_tests/diameter_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/diameter_test.cpp.i
.PHONY : test/toptree_tests/diameter_test.cpp.i

test/toptree_tests/diameter_test.s: test/toptree_tests/diameter_test.cpp.s
.PHONY : test/toptree_tests/diameter_test.s

# target to generate assembly for a file
test/toptree_tests/diameter_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/diameter_test.cpp.s
.PHONY : test/toptree_tests/diameter_test.cpp.s

test/toptree_tests/max_weight_in_component_test.o: test/toptree_tests/max_weight_in_component_test.cpp.o
.PHONY : test/toptree_tests/max_weight_in_component_test.o

# target to build an object file
test/toptree_tests/max_weight_in_component_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/max_weight_in_component_test.cpp.o
.PHONY : test/toptree_tests/max_weight_in_component_test.cpp.o

test/toptree_tests/max_weight_in_component_test.i: test/toptree_tests/max_weight_in_component_test.cpp.i
.PHONY : test/toptree_tests/max_weight_in_component_test.i

# target to preprocess a source file
test/toptree_tests/max_weight_in_component_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/max_weight_in_component_test.cpp.i
.PHONY : test/toptree_tests/max_weight_in_component_test.cpp.i

test/toptree_tests/max_weight_in_component_test.s: test/toptree_tests/max_weight_in_component_test.cpp.s
.PHONY : test/toptree_tests/max_weight_in_component_test.s

# target to generate assembly for a file
test/toptree_tests/max_weight_in_component_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/max_weight_in_component_test.cpp.s
.PHONY : test/toptree_tests/max_weight_in_component_test.cpp.s

test/toptree_tests/max_weight_on_path_test.o: test/toptree_tests/max_weight_on_path_test.cpp.o
.PHONY : test/toptree_tests/max_weight_on_path_test.o

# target to build an object file
test/toptree_tests/max_weight_on_path_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/max_weight_on_path_test.cpp.o
.PHONY : test/toptree_tests/max_weight_on_path_test.cpp.o

test/toptree_tests/max_weight_on_path_test.i: test/toptree_tests/max_weight_on_path_test.cpp.i
.PHONY : test/toptree_tests/max_weight_on_path_test.i

# target to preprocess a source file
test/toptree_tests/max_weight_on_path_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/max_weight_on_path_test.cpp.i
.PHONY : test/toptree_tests/max_weight_on_path_test.cpp.i

test/toptree_tests/max_weight_on_path_test.s: test/toptree_tests/max_weight_on_path_test.cpp.s
.PHONY : test/toptree_tests/max_weight_on_path_test.s

# target to generate assembly for a file
test/toptree_tests/max_weight_on_path_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/toptree_tests/max_weight_on_path_test.cpp.s
.PHONY : test/toptree_tests/max_weight_on_path_test.cpp.s

test/tree_tests/tree_test.o: test/tree_tests/tree_test.cpp.o
.PHONY : test/tree_tests/tree_test.o

# target to build an object file
test/tree_tests/tree_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/tree_tests/tree_test.cpp.o
.PHONY : test/tree_tests/tree_test.cpp.o

test/tree_tests/tree_test.i: test/tree_tests/tree_test.cpp.i
.PHONY : test/tree_tests/tree_test.i

# target to preprocess a source file
test/tree_tests/tree_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/tree_tests/tree_test.cpp.i
.PHONY : test/tree_tests/tree_test.cpp.i

test/tree_tests/tree_test.s: test/tree_tests/tree_test.cpp.s
.PHONY : test/tree_tests/tree_test.s

# target to generate assembly for a file
test/tree_tests/tree_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/tree_tests/tree_test.cpp.s
.PHONY : test/tree_tests/tree_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... main"
	@echo "... tests"
	@echo "... src/connected.o"
	@echo "... src/connected.i"
	@echo "... src/connected.s"
	@echo "... src/cover_level.o"
	@echo "... src/cover_level.i"
	@echo "... src/cover_level.s"
	@echo "... src/find_size.o"
	@echo "... src/find_size.i"
	@echo "... src/find_size.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/two_edge_cluster.o"
	@echo "... src/two_edge_cluster.i"
	@echo "... src/two_edge_cluster.s"
	@echo "... src/two_edge_connected.o"
	@echo "... src/two_edge_connected.i"
	@echo "... src/two_edge_connected.s"
	@echo "... test/2_edge_tests/connected_test.o"
	@echo "... test/2_edge_tests/connected_test.i"
	@echo "... test/2_edge_tests/connected_test.s"
	@echo "... test/2_edge_tests/cover_level_test.o"
	@echo "... test/2_edge_tests/cover_level_test.i"
	@echo "... test/2_edge_tests/cover_level_test.s"
	@echo "... test/2_edge_tests/find_size_test.o"
	@echo "... test/2_edge_tests/find_size_test.i"
	@echo "... test/2_edge_tests/find_size_test.s"
	@echo "... test/toptree_tests/add_common_weight_test.o"
	@echo "... test/toptree_tests/add_common_weight_test.i"
	@echo "... test/toptree_tests/add_common_weight_test.s"
	@echo "... test/toptree_tests/diameter_test.o"
	@echo "... test/toptree_tests/diameter_test.i"
	@echo "... test/toptree_tests/diameter_test.s"
	@echo "... test/toptree_tests/max_weight_in_component_test.o"
	@echo "... test/toptree_tests/max_weight_in_component_test.i"
	@echo "... test/toptree_tests/max_weight_in_component_test.s"
	@echo "... test/toptree_tests/max_weight_on_path_test.o"
	@echo "... test/toptree_tests/max_weight_on_path_test.i"
	@echo "... test/toptree_tests/max_weight_on_path_test.s"
	@echo "... test/tree_tests/tree_test.o"
	@echo "... test/tree_tests/tree_test.i"
	@echo "... test/tree_tests/tree_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

