if(EXISTS "/home/inocxh/Dokumenter/DTU/6.semester/bachelor/top-trees/tests_tests-b12d07c.cmake")
  include("/home/inocxh/Dokumenter/DTU/6.semester/bachelor/top-trees/tests_tests-b12d07c.cmake")
else()
  add_test(tests_NOT_BUILT-b12d07c tests_NOT_BUILT-b12d07c)
endif()
